version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "semiannually"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "yearly"
  - package-ecosystem: "docker"
    directories:
      - "/packages/*"
    schedule:
      interval: "monthly"
