name: Release API (Bun)

on:
  workflow_dispatch:

jobs:
  api-docker:
    name: Build API Docker Image
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        # with:
        #   ref: main

      - name: Get API version
        id: version
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF##*/}")
          echo "version=$BRANCH_NAME" >> $GITHUB_OUTPUT
        # VERSION=$(node -p "require('./packages/api/package.json').version")
        # echo "version=$VERSION" >> $GITHUB_OUTPUT

      # - name: Add support for more platforms with QEMU
      #   uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: üç∫ Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./packages/api/Dockerfile
          # platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            subztep/kellemes-api:latest
            subztep/kellemes-api:${{ steps.version.outputs.version }}
