name: Release API (Bun)

on:
  workflow_dispatch:

jobs:
  api-docker:
    name: Build API Docker Image
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: main

      - name: Get API version
        id: version
        run: |
          VERSION=$(node -p "require('./packages/api/package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Add support for more platforms with QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: üç∫ Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: "{context}/packages/api/Dockerfile"
          push: true
          tags: |
            ${{ vars.DOCKER_IMAGE }}:latest
            ${{ vars.DOCKER_IMAGE }}:${{ steps.version.outputs.version }}

  release:
    needs: api-docker
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
